all: ProjectLCoreDocs AIPlayerExampleDocs

ProjectLCoreDocs: ../ProjectL-CLI/ProjectLCoreDocs/Help
	mkdir -p ProjectLCoreDocs
	cp -r ../ProjectL-CLI/ProjectLCoreDocs/Help/* ProjectLCoreDocs

AIPlayerExampleDocs: ../ProjectL-CLI/AIPlayerExampleDocs/Help
	mkdir -p AIPlayerExampleDocs
	cp -r ../ProjectL-CLI/AIPlayerExampleDocs/Help/* AIPlayerExampleDocs
