all: ProjectLCoreDocs SimpleAIPlayerDocs

clean:
	rm -rf ProjectLCoreDocs SimpleAIPlayerDocs

ProjectLCoreDocs: ../ProjectL-CLI/ProjectLCoreDocs/Help
	cp -r ../ProjectL-CLI/ProjectLCoreDocs/Help ProjectLCoreDocs

SimpleAIPlayerDocs: ../ProjectL-CLI/SimpleAIPlayerDocs/Help
	cp -r ../ProjectL-CLI/SimpleAIPlayerDocs/Help SimpleAIPlayerDocs
