all: ProjectLCoreDocs AIPlayerExampleDocs

clean:
	rm -rf ProjectLCoreDocs AIPlayerExampleDocs

ProjectLCoreDocs: ../ProjectL-CLI/ProjectLCoreDocs/Help
	cp -r ../ProjectL-CLI/ProjectLCoreDocs/Help ProjectLCoreDocs

AIPlayerExampleDocs: ../ProjectL-CLI/AIPlayerExampleDocs/Help
	cp -r ../ProjectL-CLI/AIPlayerExampleDocs/Help AIPlayerExampleDocs
